baseURL = 'https://html-graph.github.io/'
languageCode = 'en-us'
title = 'HTMLGraph'

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = 0.5
