baseURL = 'https://html-graph.github.io/'
languageCode = 'en-us'
title = 'HTMLGraph'
description="JavaScript library for building interactive graphs with HTML and CSS."
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[taxonomies]
  category = "categories"
  tag = "tags"
